import "fake-indexeddb/auto";
import { beforeEach, describe, expect, it } from "vitest";
import { LocalArtifactDraftStore, LocalThreadStore } from "../src/adapters/browser/local-stores";
import type { Thread } from "../src/domain/types";

const thread = (id: string): Thread => ({ schemaVersion: 1, id: id as Thread["id"], title: `Topic ${id}`, createdAt: "2026-01-01T00:00:00.000Z" as Thread["createdAt"], updatedAt: "2026-01-01T00:00:00.000Z" as Thread["updatedAt"], modelRef: "fixture/model", searchRef: "fixture/search", turns: [] });
beforeEach(() => { indexedDB = new IDBFactory(); });
describe("LocalThreadStore", () => { it("round-trips threads, summaries, and backups", async () => { const store = new LocalThreadStore(); await store.save(thread("one")); expect(await store.load("one")).toMatchObject({ title: "Topic one" }); expect((await store.list())[0].id).toBe("one"); const backup = await store.exportData(); const other = new LocalThreadStore(); expect((await other.inspectImport(backup)).conflicts).toBe(1); expect((await other.importData(backup, { onConflict: "skip" })).skipped).toEqual(["one"]); }); it("replaces or skips conflicts", async () => { const store = new LocalThreadStore(); await store.save(thread("one")); const backup = { backupVersion: 1 as const, exportedAt: "2026-01-01T00:00:00.000Z", threads: [{ schemaVersion: 1 as const, thread: { ...thread("one"), title: "updated" } }] }; expect((await store.importData(backup, { onConflict: "skip" })).skipped).toEqual(["one"]); expect((await store.importData(backup, { onConflict: "replace" })).replaced).toEqual(["one"]); expect((await store.load("one"))?.title).toBe("updated"); }); });
describe("backup recovery", () => { it("reports malformed backups without throwing", async () => { const store = new LocalThreadStore(); const preview = await store.inspectImport({ backupVersion: 99, threads: null } as never); expect(preview.issues).toHaveLength(1); const report = await store.importData({ backupVersion: 99, threads: null } as never, { onConflict: "skip" }); expect(report.added).toEqual([]); }); });
describe("LocalArtifactDraftStore", () => { it("resumes drafts by unique source key", async () => { const store = new LocalArtifactDraftStore(); const draft = { schemaVersion: 1 as const, id: "draft-1" as never, threadId: "one" as never, sourceKey: "one:topic:transcript", format: "transcript" as const, scope: "topic" as const, markdown: "# draft", sourceUpdatedAt: "2026-01-01T00:00:00.000Z" as never, dirty: true, createdAt: "2026-01-01T00:00:00.000Z" as never, updatedAt: "2026-01-01T00:00:00.000Z" as never }; await store.save(draft); expect(await store.loadBySourceKey(draft.sourceKey)).toMatchObject({ markdown: "# draft" }); }); });
