import "fake-indexeddb/auto";
import { act, cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { BrandBox } from "../src/ui/boxes/BrandBox";
import { EvidenceBox } from "../src/ui/boxes/EvidenceBox";
import { PromptBox } from "../src/ui/boxes/PromptBox";
import { SettingsBox } from "../src/ui/boxes/SettingsBox";
import { ThreadsBox } from "../src/ui/boxes/ThreadsBox";
import { UnlockBox } from "../src/ui/boxes/UnlockBox";
import { TranscriptBox } from "../src/ui/boxes/TranscriptBox";
import { rankThreads, transcriptItems } from "../src/ui/boxes/box-policies";
import type { Thread, ThreadSummary } from "../src/domain/types";

afterEach(() => { cleanup(); vi.useRealTimers(); vi.restoreAllMocks(); });
const source = { sourceId: "src_1" as never, title: "Source", url: "https://example.com", canonicalUrl: "https://example.com", displayUrl: "example.com" };
const thread: Thread = { schemaVersion: 3, id: "thread_1" as never, title: "Topic", createdAt: "2026-01-01T00:00:00.000Z" as never, updatedAt: "2026-01-01T00:00:00.000Z" as never, sources: [ { ...source, ordinal: 1 } ], turns: [], legacyArchive: [{ id: "legacy_1" as never, originalIndex: 0, legacyKind: "chat", legacyStatus: "completed", createdAt: "2026-01-01T00:00:00.000Z" as never, finishedAt: "2026-01-01T00:00:00.000Z" as never, request: "Old question", answerMarkdown: "old answer [[cite:missing]]", destinations: [] }], };
const summaries: ThreadSummary[] = [{ id: "thread_1" as never, title: "Topic", createdAt: "2026-01-01T00:00:00.000Z" as never, updatedAt: "2026-01-02T00:00:00.000Z" as never, turnCount: 1, legacyArchiveCount: 0 }];

describe("v3 product boxes", () => {
  it("brands only emit new-thread intent", () => { const onIntent = vi.fn(); render(<BrandBox onIntent={onIntent} />); fireEvent.click(screen.getByRole("button", { name: "New topic" })); expect(onIntent).toHaveBeenCalledWith({ type: "new_thread_requested" }); });
  it("rotates the cleaned-up brand treatment without changing its accessible target", () => { vi.useFakeTimers(); const onIntent = vi.fn(); render(<BrandBox onIntent={onIntent} />); const brand = screen.getByRole("button", { name: "New topic" }); expect(brand).toHaveTextContent("take chances"); act(() => { vi.advanceTimersByTime(3000); }); expect(brand).toHaveTextContent("make mistakes"); expect(brand).toHaveAttribute("type", "button"); });
  it("cycles the native prompt caret through accent tokens", () => { vi.useFakeTimers(); const onIntent = vi.fn(); const onChange = vi.fn(); render(<PromptBox value="" onChange={onChange} onIntent={onIntent} />); const prompt = screen.getByLabelText("Search query"); expect(prompt).toHaveClass("prompt-caret-cycle"); expect(prompt).toHaveStyle({ caretColor: "var(--accent-1)" }); act(() => { vi.advanceTimersByTime(1500); }); expect(prompt).toHaveStyle({ caretColor: "var(--accent-2)" }); });
  it("suggests explicit search and research commands while keeping Escape local", () => { const onIntent = vi.fn(); const onChange = vi.fn(); render(<PromptBox value="/" onChange={onChange} onIntent={onIntent} />); const prompt = screen.getByLabelText("Search query"); expect(screen.getByRole("option", { name: "/search" })).toBeInTheDocument(); expect(screen.getByRole("option", { name: "/research" })).toBeInTheDocument(); expect(prompt).toHaveAttribute("placeholder", "ask anything · /search for ranked links"); fireEvent.keyDown(prompt, { key: "Escape" }); expect(screen.queryByRole("listbox")).not.toBeInTheDocument(); });
  it("requires inline deletion confirmation and gives Escape local precedence", () => { const onIntent = vi.fn(); render(<ThreadsBox state={{ threads: summaries }} onIntent={onIntent} />); const search = screen.getByLabelText("Find threads"); fireEvent.click(screen.getByRole("button", { name: "Delete Topic" })); expect(screen.getByRole("group", { name: "Confirm deletion of Topic" })).toBeInTheDocument(); fireEvent.keyDown(search, { key: "Escape" }); expect(screen.queryByRole("group", { name: "Confirm deletion of Topic" })).not.toBeInTheDocument(); expect(onIntent).not.toHaveBeenCalled(); fireEvent.keyDown(search, { key: "Escape" }); expect(onIntent).toHaveBeenCalledWith({ type: "route_escape_requested" }); fireEvent.click(screen.getByRole("button", { name: "Delete Topic" })); expect(screen.getByRole("group", { name: "Confirm deletion of Topic" })).toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Delete" })); expect(onIntent).toHaveBeenCalledWith({ type: "thread_delete_requested", threadId: "thread_1" }); });
  it("reserves the thread delete action column through confirmation", () => { const onIntent = vi.fn(); render(<ThreadsBox state={{ threads: summaries }} onIntent={onIntent} />); const row = screen.getByRole("button", { name: "Delete Topic" }).closest("li"); expect(row?.className).toContain("threadRow"); fireEvent.click(screen.getByRole("button", { name: "Delete Topic" })); expect(screen.getByRole("group", { name: "Confirm deletion of Topic" }).className).toContain("threadActions"); });
  it("labels archive history and leaves unknown citations inert", () => { const onIntent = vi.fn(); render(<TranscriptBox thread={thread} sources={[source]} onIntent={onIntent} />); expect(screen.getByText("legacy, not evidence-verified")).toBeInTheDocument(); expect(screen.getByLabelText("Topic scrollback")).toHaveTextContent("[[cite:missing]]"); expect(screen.queryByRole("link", { name: "missing" })).not.toBeInTheDocument(); expect(onIntent).not.toHaveBeenCalled(); });
  it("keeps evidence sources in one ordered full-width region with constellation accents", () => { const onIntent = vi.fn(); const second = { ...source, sourceId: "src_2" as never, title: "Second source" }; render(<EvidenceBox sources={[source, second]} onIntent={onIntent} />); const region = screen.getByRole("complementary", { name: "Evidence" }); const links = region.querySelectorAll("a"); expect(region.querySelector("ul")?.children).toHaveLength(2); expect(region.querySelectorAll("li")[0]).toHaveTextContent("Source"); expect(region.querySelectorAll("li")[1]).toHaveTextContent("Second source"); expect(links[0].className).toContain("sourceAccent"); expect(links[0].getAttribute("style")).toContain("--relational-accent"); });
  it("leaves settings on Escape", () => { const onIntent = vi.fn(); render(<SettingsBox values={{ theme: "auto", colorScheme: "mono", primaryAccent: "default" }} onIntent={onIntent} />); fireEvent.keyDown(screen.getByRole("region", { name: "Settings" }), { key: "Escape" }); expect(onIntent).toHaveBeenCalledWith({ type: "route_escape_requested" }); });
  it("clears passphrases before emitting submit intent", () => { const onIntent = vi.fn(); render(<UnlockBox onIntent={onIntent} />); const input = screen.getByLabelText("Passphrase"); fireEvent.change(input, { target: { value: "secret" } }); fireEvent.submit(input); expect(onIntent).toHaveBeenCalledWith({ type: "passphrase_submitted", passphrase: "secret" }); expect(input).toHaveValue(""); });
  it("orders transcript archive items deterministically and ranks threads", () => { expect(transcriptItems(thread)[0].kind).toBe("legacy"); expect(rankThreads(summaries, "top")).toHaveLength(1); });
});
