import "fake-indexeddb/auto";
import { act, cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { BrandBox } from "../src/ui/boxes/BrandBox";
import { EvidenceBox } from "../src/ui/boxes/EvidenceBox";
import { PromptBox } from "../src/ui/boxes/PromptBox";
import { SettingsBox } from "../src/ui/boxes/SettingsBox";
import { ThreadsBox } from "../src/ui/boxes/ThreadsBox";
import { UnlockBox } from "../src/ui/boxes/UnlockBox";
import { TranscriptBox } from "../src/ui/boxes/TranscriptBox";
import { rankThreads, transcriptItems } from "../src/ui/boxes/box-policies";
import type { Thread, ThreadSummary } from "../src/domain/types";

afterEach(() => { cleanup(); vi.useRealTimers(); vi.restoreAllMocks(); });
const source = { sourceId: "src_1" as never, title: "Source", url: "https://example.com", canonicalUrl: "https://example.com", displayUrl: "example.com" };
const thread: Thread = { schemaVersion: 3, id: "thread_1" as never, title: "Topic", createdAt: "2026-01-01T00:00:00.000Z" as never, updatedAt: "2026-01-01T00:00:00.000Z" as never, sources: [ { ...source, ordinal: 1 } ], turns: [], legacyArchive: [{ id: "legacy_1" as never, originalIndex: 0, legacyKind: "chat", legacyStatus: "completed", createdAt: "2026-01-01T00:00:00.000Z" as never, finishedAt: "2026-01-01T00:00:00.000Z" as never, request: "Old question", answerMarkdown: "old answer [[cite:missing]]", destinations: [] }], };
const summaries: ThreadSummary[] = [{ id: "thread_1" as never, title: "Topic", createdAt: "2026-01-01T00:00:00.000Z" as never, updatedAt: "2026-01-02T00:00:00.000Z" as never, turnCount: 1, legacyArchiveCount: 0 }];

describe("v3 product boxes", () => {
  it("brands only emit new-thread intent", () => { const onIntent = vi.fn(); render(<BrandBox onIntent={onIntent} />); fireEvent.click(screen.getByRole("button", { name: "New topic" })); expect(onIntent).toHaveBeenCalledWith({ type: "new_thread_requested" }); });
  it("rotates the cleaned-up brand treatment without changing its accessible target", () => { vi.useFakeTimers(); const onIntent = vi.fn(); render(<BrandBox onIntent={onIntent} />); const brand = screen.getByRole("button", { name: "New topic" }); expect(brand).toHaveTextContent("take chances"); act(() => { vi.advanceTimersByTime(3000); }); expect(brand).toHaveTextContent("make mistakes"); expect(brand).toHaveAttribute("type", "button"); });
  it("keeps the prompt hint playful and styles the native caret", () => { const onIntent = vi.fn(); const onChange = vi.fn(); render(<PromptBox value="" onChange={onChange} onIntent={onIntent} />); const prompt = screen.getByLabelText("Search query"); expect(prompt).toHaveAttribute("placeholder", "???"); expect(prompt.className).toContain("promptInput"); expect(prompt.style.caretColor).toBeTruthy(); expect(prompt.nextElementSibling).toBeNull(); });
  it("rotates the native caret through the selected scheme palette while focused", () => { vi.useFakeTimers(); document.documentElement.style.setProperty("--accent-1", "#111111"); document.documentElement.style.setProperty("--accent-2", "#222222"); const onIntent = vi.fn(); const onChange = vi.fn(); render(<PromptBox value="" onChange={onChange} onIntent={onIntent} />); const prompt = screen.getByLabelText("Search query"); prompt.focus(); expect(prompt.style.caretColor).toBe("#111111"); act(() => { vi.advanceTimersByTime(2000); }); expect(prompt.style.caretColor).toBe("#222222"); prompt.blur(); act(() => { vi.advanceTimersByTime(2000); }); expect(prompt.style.caretColor).toBe("#111111"); document.documentElement.style.removeProperty("--accent-1"); document.documentElement.style.removeProperty("--accent-2"); });
  it("suggests link and navigation commands while keeping Escape local", () => { const onIntent = vi.fn(); const onChange = vi.fn(); render(<PromptBox value="/" onChange={onChange} onIntent={onIntent} />); const prompt = screen.getByLabelText("Search query"); expect(screen.getByRole("option", { name: /link/ })).toBeInTheDocument(); expect(screen.getByRole("listbox", { name: "Commands" })).toHaveClass("ui-listbox-menu--overlay"); expect(screen.queryByRole("option", { name: "/research" })).not.toBeInTheDocument(); expect(prompt).toHaveAttribute("placeholder", "???"); fireEvent.keyDown(prompt, { key: "Tab" }); expect(onChange).toHaveBeenCalledWith("/new "); expect(screen.queryByRole("listbox")).not.toBeInTheDocument(); });
  it("uses click to autocomplete without submitting and spaces link commands", () => { const onIntent = vi.fn(); const onChange = vi.fn(); render(<PromptBox value="/" onChange={onChange} onIntent={onIntent} />); fireEvent.click(screen.getByRole("option", { name: /link/ })); expect(onChange).toHaveBeenCalledWith("/link "); expect(onIntent).not.toHaveBeenCalled(); expect(screen.queryByRole("listbox")).not.toBeInTheDocument(); });
  it("supports Delete-to-confirm and Enter-to-delete thread hotkeys", () => { const onIntent = vi.fn(); render(<ThreadsBox state={{ threads: summaries }} onIntent={onIntent} />); const search = screen.getByLabelText("Find threads"); expect(document.activeElement).toBe(search); fireEvent.keyDown(search, { key: "Delete" }); expect(screen.getByRole("group", { name: "Confirm deletion of Topic" })).toBeInTheDocument(); expect(onIntent).not.toHaveBeenCalled(); fireEvent.keyDown(search, { key: "Enter" }); expect(onIntent).toHaveBeenCalledWith({ type: "thread_delete_requested", threadId: "thread_1" }); expect(screen.queryByRole("group", { name: "Confirm deletion of Topic" })).not.toBeInTheDocument(); });
  it("supports Backspace confirmation and y/n confirmation controls", () => { const onIntent = vi.fn(); render(<ThreadsBox state={{ threads: summaries }} onIntent={onIntent} />); const search = screen.getByLabelText("Find threads"); fireEvent.keyDown(search, { key: "Backspace" }); expect(screen.getByRole("group", { name: "Confirm deletion of Topic" })).toBeInTheDocument(); fireEvent.keyDown(search, { key: "n" }); expect(screen.queryByRole("group", { name: "Confirm deletion of Topic" })).not.toBeInTheDocument(); fireEvent.keyDown(search, { key: "Backspace" }); fireEvent.keyDown(search, { key: "y" }); expect(onIntent).toHaveBeenCalledWith({ type: "thread_delete_requested", threadId: "thread_1" }); });
  it("requires inline deletion confirmation and gives Escape local precedence", () => { const onIntent = vi.fn(); render(<ThreadsBox state={{ threads: summaries }} onIntent={onIntent} />); const search = screen.getByLabelText("Find threads"); fireEvent.click(screen.getByRole("button", { name: "Delete Topic" })); expect(screen.getByRole("group", { name: "Confirm deletion of Topic" })).toBeInTheDocument(); fireEvent.keyDown(search, { key: "Escape" }); expect(screen.queryByRole("group", { name: "Confirm deletion of Topic" })).not.toBeInTheDocument(); expect(onIntent).not.toHaveBeenCalled(); fireEvent.keyDown(search, { key: "Escape" }); expect(onIntent).toHaveBeenCalledWith({ type: "route_escape_requested" }); fireEvent.click(screen.getByRole("button", { name: "Delete Topic" })); expect(screen.getByRole("group", { name: "Confirm deletion of Topic" })).toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Delete" })); expect(onIntent).toHaveBeenCalledWith({ type: "thread_delete_requested", threadId: "thread_1" }); });
  it("reserves the thread delete action column through confirmation", () => { const onIntent = vi.fn(); render(<ThreadsBox state={{ threads: summaries }} onIntent={onIntent} />); const row = screen.getByRole("button", { name: "Delete Topic" }).closest("li"); expect(row?.className).toContain("threadRow"); fireEvent.click(screen.getByRole("button", { name: "Delete Topic" })); expect(screen.getByRole("group", { name: "Confirm deletion of Topic" }).className).toContain("threadActions"); });
  it("labels archive history and leaves unknown citations inert", () => { const onIntent = vi.fn(); render(<TranscriptBox thread={thread} sources={[source]} onIntent={onIntent} />); expect(screen.getByText("legacy, not evidence-verified")).toBeInTheDocument(); expect(screen.getByLabelText("Topic scrollback")).toHaveTextContent("[[cite:missing]]"); expect(screen.queryByRole("link", { name: "missing" })).not.toBeInTheDocument(); expect(onIntent).not.toHaveBeenCalled(); });
  it("separates each response from the next user turn", () => { const onIntent = vi.fn(); const next = { ...thread.legacyArchive[0], id: "legacy_2" as never, originalIndex: 1, createdAt: "2026-01-02T00:00:00.000Z" as never, finishedAt: "2026-01-02T00:00:00.000Z" as never, request: "Next question" }; render(<TranscriptBox thread={{ ...thread, legacyArchive: [...thread.legacyArchive, next] }} sources={[source]} onIntent={onIntent} />); const transcript = screen.getByLabelText("Topic scrollback"); const sections = transcript.querySelectorAll("section"); expect(sections).toHaveLength(2); expect(sections[1].previousElementSibling?.tagName).toBe("HR"); });
  it("keeps evidence sources in one ordered full-width region with constellation accents", () => { const onIntent = vi.fn(); const second = { ...source, sourceId: "src_2" as never, title: "Second source", snippet: "<strong>Important</strong> detail <script>alert(1)</script>" }; render(<EvidenceBox sources={[source, second]} onIntent={onIntent} />); const region = screen.getByRole("complementary", { name: "Evidence" }); const links = region.querySelectorAll("a"); expect(region.querySelector("ul")?.children).toHaveLength(2); expect(region.querySelectorAll("li")[0]).toHaveTextContent("Source"); expect(region.querySelectorAll("li")[1]).toHaveTextContent("Second source"); expect(region.querySelector("strong")).toHaveTextContent("Important"); expect(region.querySelector("script")).toBeNull(); expect(links[0].className).toContain("sourceAccent"); expect(links[0].getAttribute("style")).toContain("--relational-accent"); });
  it("uses a bounded detached media attachment instead of the snippet without changing source decoration", () => { const onIntent = vi.fn(); const image = { ...source, kind: "image", sourceId: "src_image" as never, title: "Image source", imageUrl: "https://cdn.example/image.jpg", url: "https://cdn.example/image.jpg", canonicalUrl: "https://cdn.example/image.jpg", sourcePageUrl: "https://example.com/page", thumbnailUrl: "https://cdn.example/thumb.jpg", snippet: "This should be hidden" } as never; render(<EvidenceBox sources={[source, image]} onIntent={onIntent} />); const region = screen.getByRole("complementary", { name: "Evidence" }); const linkTitle = screen.getByRole("link", { name: "Link result: Source" }); const imageTitle = screen.getByRole("link", { name: "Image result: Image source" }); expect(linkTitle.className).toBe(imageTitle.className); expect(screen.queryByText("This should be hidden")).not.toBeInTheDocument(); const thumbnail = region.querySelector("img"); expect(thumbnail?.className).toContain("mediaThumbnail"); expect(screen.queryByRole("link", { name: "Open image" })).not.toBeInTheDocument(); expect(screen.getByRole("link", { name: "Image result preview: Image source" })).toHaveAttribute("href", "https://example.com/page"); });
  it("standardizes appearance controls and removes backup UI", () => { const onIntent = vi.fn(); render(<SettingsBox values={{ theme: "auto", colorScheme: "mono", primaryAccent: "default" }} onIntent={onIntent} />); expect(screen.getByText("Appearance").parentElement?.className).toContain("themeControl"); expect(screen.getByText("Color scheme").parentElement?.className).toContain("themeControl"); expect(screen.getByText("Primary accent").parentElement?.className).toContain("themeControl"); expect(screen.queryByRole("button", { name: "Preview backup import" })).not.toBeInTheDocument(); expect(screen.queryByRole("dialog", { name: "Backup preview" })).not.toBeInTheDocument(); });
  it("uses slash-command-style settings menus for preference selection", () => { const onIntent = vi.fn(); render(<SettingsBox values={{ theme: "auto", colorScheme: "mono", primaryAccent: "default" }} onIntent={onIntent} />); const appearance = screen.getByRole("button", { name: "Appearance" }); fireEvent.click(appearance); const menu = screen.getByRole("listbox", { name: "Appearance" }); expect(menu).toHaveClass("ui-listbox-menu--overlay"); expect(menu).toHaveClass("settings-menu"); expect(menu.querySelectorAll('[role="option"]')).toHaveLength(3); expect(screen.getByRole("option", { name: "dark" })).toBeInTheDocument(); fireEvent.click(screen.getByRole("option", { name: "dark" })); expect(onIntent).toHaveBeenCalledWith({ type: "preference_changed", key: "theme", value: "dark" }); expect(screen.queryByRole("listbox", { name: "Appearance" })).not.toBeInTheDocument(); });
  it("leaves settings on Escape", () => { const onIntent = vi.fn(); render(<SettingsBox values={{ theme: "auto", colorScheme: "mono", primaryAccent: "default" }} onIntent={onIntent} />); fireEvent.keyDown(screen.getByRole("region", { name: "Settings" }), { key: "Escape" }); expect(onIntent).toHaveBeenCalledWith({ type: "route_escape_requested" }); });
  it("clears passphrases before emitting submit intent", () => { const onIntent = vi.fn(); render(<UnlockBox onIntent={onIntent} />); const input = screen.getByLabelText("Passphrase"); fireEvent.change(input, { target: { value: "secret" } }); fireEvent.submit(input); expect(onIntent).toHaveBeenCalledWith({ type: "passphrase_submitted", passphrase: "secret" }); expect(input).toHaveValue(""); });
  it("orders transcript archive items deterministically and ranks threads", () => { expect(transcriptItems(thread)[0].kind).toBe("legacy"); expect(rankThreads(summaries, "top")).toHaveLength(1); });
});
