import { FormEvent, useEffect, useState } from "react";
import { Link, Route, Routes, useNavigate, useSearchParams } from "react-router-dom";
import styles from "./App.module.css";

type Result = { sourceId: string; title: string; url: string; displayUrl: string; snippet?: string };
type StreamState = { stage: string; answer: string; sources: Result[]; error?: string };

function Unlock() { const [passphrase, setPassphrase] = useState(""); const [message, setMessage] = useState(""); return <main className={styles.center}><section className={styles.card} aria-labelledby="unlock-title"><p className={styles.kicker}>private research desk</p><h1 id="unlock-title">dorothy-ann</h1><p>This research desk is private.</p><form onSubmit={async (event) => { event.preventDefault(); const response = await fetch("/api/auth/passphrase", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ passphrase }) }); setMessage(response.ok ? "Unlocked." : "That passphrase did not work."); }}><label htmlFor="passphrase">Passphrase</label><input id="passphrase" type="password" value={passphrase} onChange={(event) => setPassphrase(event.target.value)} autoComplete="current-password" /><button type="submit">Unlock</button></form>{message && <p role="status">{message}</p>}</section></main>; }

function Home() { const [query, setQuery] = useState(""); const [mode, setMode] = useState<"lookup" | "research">("lookup"); const navigate = useNavigate(); const inferred = query.trimEnd().endsWith("?"); const activeMode = mode === "lookup" && inferred ? "research" : mode; const submit = (event: FormEvent) => { event.preventDefault(); if (query.trim()) navigate(`/topics/new?mode=${activeMode}&q=${encodeURIComponent(query.trim())}`); }; return <main className={styles.shell}><header className={styles.header}><button className={styles.iconButton} aria-label="Open topics">☰</button><Link to="/" className={styles.brand}>dorothy-ann</Link><button className={styles.iconButton} aria-label="New topic">＋</button></header><section className={styles.hero}><p className={styles.kicker}>curious · prepared · evidence-oriented</p><h1>What should we look up?</h1><form onSubmit={submit} className={styles.queryForm}><input aria-label="Search query" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Ask a question or search for something" autoFocus /><div className={styles.controls}><select aria-label="Query mode" value={activeMode} onChange={(event) => setMode(event.target.value as "lookup" | "research")}><option value="lookup">lookup</option><option value="research">research</option></select><button type="submit">{activeMode === "research" ? "Ask Dorothy Ann" : "Go"}</button></div></form><p className={styles.hint}>Add <strong>?</strong> to ask Dorothy Ann to research.</p></section><p className={styles.recent}>Recent topics will stay in this browser.</p></main>; }

async function readResearchStream(response: Response, update: (state: StreamState) => void) { const text = await response.text(); const blocks = text.split("\n\n").filter(Boolean); let state: StreamState = { stage: "starting", answer: "", sources: [] }; for (const block of blocks) { const event = block.match(/^event: (.+)$/m)?.[1]; const data = block.match(/^data: (.+)$/m)?.[1]; if (!event || !data) continue; const payload = JSON.parse(data) as Record<string, unknown>; if (event === "research.sources") state = { ...state, stage: "sources found", sources: (payload.sources as Result[]) ?? [] }; else if (event === "research.extraction") state = { ...state, stage: "extracting evidence" }; else if (event === "answer.delta") state = { ...state, stage: "complete", answer: state.answer + String(payload.markdown ?? "") }; else if (event === "turn.failed") state = { ...state, stage: "failed", error: String(payload.code ?? "research failed") }; update(state); } }

function Topic() { const [params] = useSearchParams(); const query = params.get("q") ?? ""; const mode = params.get("mode") ?? "lookup"; const [state, setState] = useState<StreamState>({ stage: "loading", answer: "", sources: [] }); useEffect(() => { let cancelled = false; const run = async () => { try { if (mode === "lookup") { const response = await fetch("/api/lookup", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ query }) }); if (!response.ok) throw new Error("lookup failed"); const data = await response.json() as { results: Result[] }; if (!cancelled) setState({ stage: data.results.length ? "results found" : "no results", answer: "", sources: data.results }); } else { const response = await fetch("/api/research", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ query }) }); if (!response.ok) throw new Error("research failed"); await readResearchStream(response, (next) => { if (!cancelled) setState(next); }); } } catch (error) { if (!cancelled) setState((current) => ({ ...current, stage: "failed", error: error instanceof Error ? error.message : "request failed" })); } }; void run(); return () => { cancelled = true; }; }, [mode, query]); return <main className={styles.shell}><header className={styles.header}><Link to="/" className={styles.brand}>← dorothy-ann</Link><span className={styles.kicker}>{mode}</span></header><section className={styles.topic}><p className={styles.kicker}>{state.stage}</p><h1>{query}</h1>{state.error && <p role="alert">{state.error}</p>}{state.answer && <article className={styles.answer}><p>{state.answer}</p></article>}{state.sources.length > 0 && <section aria-labelledby="sources-title"><h2 id="sources-title">{mode === "research" ? "What I found" : "Results"}</h2><ul>{state.sources.map((source) => <li key={source.sourceId}><a href={source.url} target="_blank" rel="noreferrer">{source.title}</a><small>{source.displayUrl}</small>{source.snippet && <p>{source.snippet}</p>}</li>)}</ul></section>}</section></main>; }

export function App() { return <Routes><Route path="/unlock" element={<Unlock />} /><Route path="/topics/:threadId" element={<Topic />} /><Route path="*" element={<Home />} /></Routes>; }
