import { getCookie, setCookie, deleteCookie } from "hono/cookie";
import { Hono } from "hono";
import { streamSSE } from "hono/streaming";
import { InMemoryLoginLimiter, SessionAuth } from "./auth.js";
import type { AppConfig } from "./config.js";
import { BraveSearchProvider } from "./brave.js";

export interface AppDependencies { config: AppConfig; }

export function createApp({ config }: AppDependencies) {
  const app = new Hono();
  const auth = config.APP_PASSPHRASE_SCRYPT_HASH && config.SESSION_SIGNING_KEYS ? new SessionAuth(config.APP_PASSPHRASE_SCRYPT_HASH, config.SESSION_SIGNING_KEYS) : null;
  const limiter = new InMemoryLoginLimiter();
  const searchProvider = config.BRAVE_SEARCH_API_KEY ? new BraveSearchProvider(config.BRAVE_SEARCH_API_KEY) : null;
  app.use("/api/*", async (context, next) => { context.header("Cache-Control", "no-store"); context.header("X-Content-Type-Options", "nosniff"); context.header("Referrer-Policy", "same-origin"); await next(); });
  app.get("/api/health", (context) => context.json({ ok: true, fixtureMode: config.DOROTHY_FIXTURE_MODE }));
  app.get("/api/auth/session", (context) => { const claims = auth ? auth.verifySession(getCookie(context, "__Host-dorothy-ann-session") ?? "") : null; if (!claims) return context.json({ authenticated: false }); return context.json({ authenticated: true, session: { subject: claims.subject, method: claims.method, expiresAt: new Date(claims.exp).toISOString(), absoluteExpiresAt: new Date(claims.abs).toISOString() } }); });
  app.post("/api/auth/logout", (context) => { if (auth) deleteCookie(context, "__Host-dorothy-ann-session", { path: "/" }); return context.body(null, 204); });
  app.post("/api/auth/passphrase", async (context) => { const body = await context.req.json().catch(() => null) as { passphrase?: unknown } | null; if (!body || typeof body.passphrase !== "string" || body.passphrase.length === 0) return context.json({ error: { code: "invalid_request", message: "passphrase is required" } }, 400); const key = context.req.header("x-forwarded-for") ?? "local"; const attempt = await limiter.consume(key); if (!attempt.allowed) { if (attempt.retryAfterSeconds) context.header("Retry-After", String(attempt.retryAfterSeconds)); return context.json({ error: { code: "rate_limited", message: "try again later" } }, 429); } if (!auth) { if (!config.DOROTHY_FIXTURE_MODE) return context.json({ error: { code: "service_unavailable", message: "authentication is not configured" } }, 503); return context.json({ authenticated: true, session: { subject: "owner", method: "passphrase", expiresAt: new Date(Date.now() + 7 * 86400000).toISOString(), absoluteExpiresAt: new Date(Date.now() + 30 * 86400000).toISOString() } }); } if (!(await auth.verifyPassphrase(body.passphrase))) return context.json({ error: { code: "unauthorized", message: "invalid passphrase" } }, 401); await limiter.reset(key); const session = auth.createSession(); setCookie(context, "__Host-dorothy-ann-session", session.value, { httpOnly: true, secure: true, sameSite: "Lax", path: "/", maxAge: 7 * 86400 }); return context.json({ authenticated: true, session: { subject: "owner", method: "passphrase", expiresAt: session.expiresAt, absoluteExpiresAt: session.absoluteExpiresAt } }); });
  app.post("/api/lookup", async (context) => { const body = await context.req.json().catch(() => null) as { query?: unknown } | null; if (!body || typeof body.query !== "string" || !body.query.trim() || body.query.length > 2_000) return context.json({ error: { code: "invalid_request", message: "query is required and must be bounded" } }, 400); if (searchProvider) { try { return context.json({ results: await searchProvider.search(body.query.trim(), { maxResults: config.MAX_SEARCH_RESULTS }) }); } catch (error) { const code = error instanceof Error && error.message === "provider_rate_limited" ? "rate_limited" : "service_unavailable"; return context.json({ error: { code, message: "search provider unavailable" } }, code === "rate_limited" ? 429 : 503); } } if (!config.DOROTHY_FIXTURE_MODE) return context.json({ error: { code: "service_unavailable", message: "search provider is not configured" } }, 503); return context.json({ results: [{ sourceId: "fixture-weather", rank: 1, title: `Fixture result for ${body.query.trim()}`, url: "https://example.com/fixture", canonicalUrl: "https://example.com/fixture", displayUrl: "example.com/fixture", snippet: "A safe fixture result for local development." }] }); });
  app.post("/api/turn", async (context) => { const body = await context.req.json().catch(() => null) as { query?: unknown; mode?: unknown } | null; if (!body || typeof body.query !== "string" || !body.query.trim() || body.query.length > 2_000 || (body.mode !== "chat" && body.mode !== "research")) return context.json({ error: { code: "invalid_request", message: "bounded query and mode are required" } }, 400); if (!config.DOROTHY_FIXTURE_MODE) return context.json({ error: { code: "service_unavailable", message: "chat provider is not configured" } }, 503); const turnId = crypto.randomUUID(); return streamSSE(context, async (stream) => { await stream.writeSSE({ event: "turn.started", data: JSON.stringify({ turnId, mode: body.mode }) }); if (body.mode === "research") { await stream.writeSSE({ event: "research.query", data: JSON.stringify({ query: body.query }) }); await stream.writeSSE({ event: "research.sources", data: JSON.stringify({ sources: [{ sourceId: "fixture-weather", rank: 1, title: "Fixture evidence", url: "https://example.com/fixture", canonicalUrl: "https://example.com/fixture", displayUrl: "example.com/fixture", snippet: "Fixture evidence for local development." }] }) }); } const answer = body.mode === "research" ? "According to my research…\n\nThis is a bounded fixture answer grounded in the available evidence. [[cite:fixture-weather]]" : `Fixture chat response for: ${body.query}`; await stream.writeSSE({ event: "answer.delta", data: JSON.stringify({ markdown: answer }) }); await stream.writeSSE({ event: "turn.completed", data: JSON.stringify({ turnId, usage: { searches: body.mode === "research" ? 1 : 0 } }) }); }); });
  app.post("/api/report", async (context) => { const body = await context.req.json().catch(() => null) as { title?: unknown; objective?: unknown; answer?: unknown } | null; if (!body || typeof body.title !== "string" || !body.title.trim() || typeof body.answer !== "string" || !body.answer.trim()) return context.json({ error: { code: "invalid_report_input", message: "title and answer are required" } }, 400); const markdown = [`# Dorothy Ann report: ${body.title.trim()}`, "", "## Objective", "", typeof body.objective === "string" && body.objective.trim() ? body.objective.trim() : "Not specified.", "", "## Conclusion", "", body.answer.trim(), "", "## Next actions", "", "- Validate this research context before acting on it.", "- Preserve useful decisions in durable working notes.", "", "> This is research context, not executed or independently verified work.", ""].join("\\n"); return context.json({ format: "dorothy_ann_report", scope: "answer", mimeType: "text/markdown", markdown }); });
  return app;
}
