import { getCookie, setCookie, deleteCookie } from "hono/cookie";
import { Hono } from "hono";
import { InMemoryLoginLimiter, SessionAuth } from "./auth.js";
import type { AppConfig } from "./config.js";

export interface AppDependencies { config: AppConfig; }

export function createApp({ config }: AppDependencies) {
  const app = new Hono();
  const auth = config.APP_PASSPHRASE_SCRYPT_HASH && config.SESSION_SIGNING_KEYS ? new SessionAuth(config.APP_PASSPHRASE_SCRYPT_HASH, config.SESSION_SIGNING_KEYS) : null;
  const limiter = new InMemoryLoginLimiter();
  app.use("/api/*", async (context, next) => { context.header("Cache-Control", "no-store"); context.header("X-Content-Type-Options", "nosniff"); context.header("Referrer-Policy", "same-origin"); await next(); });
  app.get("/api/health", (context) => context.json({ ok: true, fixtureMode: config.DOROTHY_FIXTURE_MODE }));
  app.get("/api/auth/session", (context) => { const claims = auth ? auth.verifySession(getCookie(context, "__Host-dorothy-ann-session") ?? "") : null; if (!claims) return context.json({ authenticated: false }); return context.json({ authenticated: true, session: { subject: claims.subject, method: claims.method, expiresAt: new Date(claims.exp).toISOString(), absoluteExpiresAt: new Date(claims.abs).toISOString() } }); });
  app.post("/api/auth/logout", (context) => { if (auth) deleteCookie(context, "__Host-dorothy-ann-session", { path: "/" }); return context.body(null, 204); });
  app.post("/api/auth/passphrase", async (context) => { const body = await context.req.json().catch(() => null) as { passphrase?: unknown } | null; if (!body || typeof body.passphrase !== "string" || body.passphrase.length === 0) return context.json({ error: { code: "invalid_request", message: "passphrase is required" } }, 400); const key = context.req.header("x-forwarded-for") ?? "local"; const attempt = await limiter.consume(key); if (!attempt.allowed) { if (attempt.retryAfterSeconds) context.header("Retry-After", String(attempt.retryAfterSeconds)); return context.json({ error: { code: "rate_limited", message: "try again later" } }, 429); } if (!auth) { if (!config.DOROTHY_FIXTURE_MODE) return context.json({ error: { code: "service_unavailable", message: "authentication is not configured" } }, 503); return context.json({ authenticated: true, session: { subject: "owner", method: "passphrase", expiresAt: new Date(Date.now() + 7 * 86400000).toISOString(), absoluteExpiresAt: new Date(Date.now() + 30 * 86400000).toISOString() } }); } if (!(await auth.verifyPassphrase(body.passphrase))) return context.json({ error: { code: "unauthorized", message: "invalid passphrase" } }, 401); await limiter.reset(key); const session = auth.createSession(); setCookie(context, "__Host-dorothy-ann-session", session.value, { httpOnly: true, secure: true, sameSite: "Lax", path: "/", maxAge: 7 * 86400 }); return context.json({ authenticated: true, session: { subject: "owner", method: "passphrase", expiresAt: session.expiresAt, absoluteExpiresAt: session.absoluteExpiresAt } }); });
  app.post("/api/lookup", async (context) => { const body = await context.req.json().catch(() => null) as { query?: unknown } | null; if (!body || typeof body.query !== "string" || !body.query.trim()) return context.json({ error: { code: "invalid_request", message: "query is required" } }, 400); if (!config.DOROTHY_FIXTURE_MODE) return context.json({ error: { code: "service_unavailable", message: "live search adapter is not configured in this scaffold" } }, 503); return context.json({ results: [{ sourceId: "fixture-weather", rank: 1, title: `Fixture result for ${body.query.trim()}`, url: "https://example.com/fixture", canonicalUrl: "https://example.com/fixture", displayUrl: "example.com/fixture", snippet: "A safe fixture result for local development." }] }); });
  return app;
}
