import { createHmac, timingSafeEqual, scrypt as scryptCallback } from "node:crypto";
import type { LoginAttemptLimiter } from "../src/ports/auth.js";

const scrypt = (password: string, salt: Buffer, keylen: number, options?: { N: number; r: number; p: number }) => new Promise<Buffer>((resolve, reject) => scryptCallback(password, salt, keylen, options ?? {}, (error, key) => error ? reject(error) : resolve(key as Buffer)));
const COOKIE = "__Host-dorothy-ann-session";
type Claims = { kid: string; subject: "owner"; method: "passphrase"; iat: number; exp: number; abs: number };
export class InMemoryLoginLimiter implements LoginAttemptLimiter { private readonly buckets = new Map<string, { count: number; resetAt: number }>(); constructor(private readonly max = 5, private readonly windowMs = 15 * 60_000) {} async consume(key: string) { const now = Date.now(); const current = this.buckets.get(key); if (!current || current.resetAt <= now) { this.buckets.set(key, { count: 1, resetAt: now + this.windowMs }); return { allowed: true }; } current.count += 1; return current.count <= this.max ? { allowed: true } : { allowed: false, retryAfterSeconds: Math.ceil((current.resetAt - now) / 1000) }; } async reset(key: string) { this.buckets.delete(key); } }
export class SessionAuth { private readonly keys: Array<{ id: string; secret: string }>; constructor(private readonly hash: string, signingKeys: string, private readonly now = () => Date.now()) { this.keys = signingKeys.split(",").filter(Boolean).map((entry, index) => { const [id, secret] = entry.includes(":") ? entry.split(/:(.*)/s, 2) : [`key-${index}`, entry]; return { id, secret }; }); if (!this.keys.length) throw new Error("SESSION_SIGNING_KEYS is required"); }
  async verifyPassphrase(passphrase: string): Promise<boolean> { const match = /^scrypt\$v1\$N=(\d+),r=(\d+),p=(\d+)\$([^$]+)\$([^$]+)$/.exec(this.hash); if (!match) return false; const [, n, r, p, salt, expected] = match; const derived = await scrypt(passphrase, Buffer.from(salt, "base64url"), 32, { N: Number(n), r: Number(r), p: Number(p) }) as Buffer; const expectedBuffer = Buffer.from(expected, "base64url"); return expectedBuffer.length === derived.length && timingSafeEqual(expectedBuffer, derived); }
  createSession(): { value: string; expiresAt: string; absoluteExpiresAt: string } { const now = this.now(); const claims: Claims = { kid: this.keys[0].id, subject: "owner", method: "passphrase", iat: now, exp: now + 7 * 86400000, abs: now + 30 * 86400000 }; return { value: this.sign(claims), expiresAt: new Date(claims.exp).toISOString(), absoluteExpiresAt: new Date(claims.abs).toISOString() }; }
  refreshSession(claims: Claims): { value: string; expiresAt: string; absoluteExpiresAt: string } {
    const now = this.now();
    const refreshed: Claims = { ...claims, exp: Math.min(now + 7 * 86400000, claims.abs) };
    return { value: this.sign(refreshed), expiresAt: new Date(refreshed.exp).toISOString(), absoluteExpiresAt: new Date(refreshed.abs).toISOString() };
  }
  verifySession(value: string): Claims | null { const [encoded, signature] = value.split("."); if (!encoded || !signature) return null; let claims: Claims; try { claims = JSON.parse(Buffer.from(encoded, "base64url").toString("utf8")) as Claims; } catch { return null; } if (claims.subject !== "owner" || claims.method !== "passphrase" || this.now() > claims.exp || this.now() > claims.abs) return null; const valid = this.keys.some(({ secret }) => { const expected = this.signature(encoded, secret); return expected.length === signature.length && timingSafeEqual(Buffer.from(expected), Buffer.from(signature)); }); return valid ? claims : null; }
  cookie(session: ReturnType<SessionAuth["createSession"]>): string { return `${COOKIE}=${session.value}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${7 * 86400}`; }
  expiredCookie(): string { return `${COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`; }
  private sign(claims: Claims): string { const encoded = Buffer.from(JSON.stringify(claims)).toString("base64url"); return `${encoded}.${this.signature(encoded, this.keys[0].secret)}`; }
  private signature(value: string, secret: string): string { return createHmac("sha256", secret).update(value).digest("base64url"); }
}
