import { lookup } from "node:dns/promises";
import { isIP } from "node:net";
import { Readability } from "@mozilla/readability";
import { parseHTML } from "linkedom";
import type { ExtractionOutcome, SearchResult } from "../src/domain/types.js";
import type { ContentExtractor, ExtractionLimits } from "../src/ports/extraction.js";

export interface ExtractorConfig { maxFetchBytes: number; maxRedirects: number; userAgent: string; minCharacters: number }
const privateIPv4 = (ip: string) => { const octets = ip.split(".").map(Number); return octets[0] === 10 || octets[0] === 127 || (octets[0] === 169 && octets[1] === 254) || (octets[0] === 172 && octets[1] >= 16 && octets[1] <= 31) || (octets[0] === 192 && octets[1] === 168) || octets[0] >= 224; };
export function isPublicAddress(address: string): boolean { if (isIP(address) === 4) return !privateIPv4(address); const normalized = address.toLowerCase(); return normalized !== "::1" && !normalized.startsWith("fc") && !normalized.startsWith("fd") && !normalized.startsWith("fe8") && !normalized.startsWith("fe9") && !normalized.startsWith("fea") && !normalized.startsWith("feb") && !normalized.startsWith("::ffff:127."); }
export async function assertSafeUrl(value: string): Promise<URL> { const url = new URL(value); if (!(["http:", "https:"].includes(url.protocol)) || url.username || url.password || (url.port && !(["80", "443"].includes(url.port)))) throw new Error("unsafe_url"); if (["localhost", "localhost.localdomain"].includes(url.hostname.toLowerCase())) throw new Error("unsafe_url"); const addresses = await lookup(url.hostname, { all: true, verbatim: true }); if (!addresses.length || addresses.some(({ address }) => !isPublicAddress(address))) throw new Error("unsafe_url"); return url; }
export class SafeContentExtractor implements ContentExtractor { constructor(private readonly config: ExtractorConfig, private readonly fetcher: typeof fetch = fetch) {}
  async extract(source: SearchResult, limits: ExtractionLimits): Promise<ExtractionOutcome> { let current: URL; try { current = await assertSafeUrl(source.url); } catch { return { sourceId: source.sourceId, status: "skipped", reason: "unsafe_url" }; } for (let redirects = 0; redirects <= this.config.maxRedirects; redirects++) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), limits.timeoutMs); try { const response = await this.fetcher(current, { redirect: "manual", signal: controller.signal, headers: { "user-agent": this.config.userAgent, accept: "text/html,text/plain;q=0.9" } }); if (response.status >= 300 && response.status < 400) { const location = response.headers.get("location"); if (!location || redirects === this.config.maxRedirects) return { sourceId: source.sourceId, status: "skipped", reason: "blocked" }; current = await assertSafeUrl(new URL(location, current).toString()); continue; } if (!response.ok) return { sourceId: source.sourceId, status: "failed", code: "fetch_failed", retryable: response.status >= 500 }; const contentType = response.headers.get("content-type")?.split(";", 1)[0].trim().toLowerCase(); if (contentType !== "text/html" && contentType !== "text/plain") return { sourceId: source.sourceId, status: "skipped", reason: "unsupported_content" }; const buffer = new Uint8Array(await response.arrayBuffer()); if (buffer.byteLength > this.config.maxFetchBytes) return { sourceId: source.sourceId, status: "failed", code: "fetch_failed", retryable: false }; const raw = new TextDecoder().decode(buffer); const text = contentType === "text/html" ? readableText(raw) : raw; const bounded = text.replace(/\s+/g, " ").trim().slice(0, limits.maxCharacters); if (bounded.length < this.config.minCharacters) return { sourceId: source.sourceId, status: "skipped", reason: "empty_content" }; return { sourceId: source.sourceId, status: "viable", page: { sourceId: source.sourceId, canonicalUrl: current.toString(), title: source.title, text: bounded, extractedAt: new Date().toISOString() as never, characterCount: bounded.length } }; } catch (error) { return { sourceId: source.sourceId, status: "failed", code: error instanceof DOMException && error.name === "AbortError" ? "timeout" : "fetch_failed", retryable: true }; } finally { clearTimeout(timer); } } return { sourceId: source.sourceId, status: "skipped", reason: "blocked" }; }
}
function readableText(html: string): string { const { document } = parseHTML(html); const article = new Readability(document as unknown as Document).parse(); return article?.textContent ?? ""; }
